// Generated by bradasm from tangnano9k/boot.s -- do not edit.
// 16 words at 0x00000000.
initial begin
    imem[0] = 32'h81000000;
    imem[1] = 32'h81100001;
    imem[2] = 32'h82000004;
    imem[3] = 32'hA0210000;
    imem[4] = 32'hD000FFFC;
    imem[5] = 32'h81000000;
    imem[6] = 32'h81000000;
    imem[7] = 32'h81000000;
    imem[8] = 32'h81000000;
    imem[9] = 32'h81000000;
    imem[10] = 32'h81000000;
    imem[11] = 32'h81000000;
    imem[12] = 32'h81000000;
    imem[13] = 32'h81000000;
    imem[14] = 32'h81000000;
    imem[15] = 32'h81000000;
end
