/* SPDX-License-Identifier: MIT */
/* bradasm -- command line driver.
 *
 * Reads an assembly file, writes a flat little-endian binary image, and can
 * print a listing and the symbol table.  The listing is the point: once you
 * have a real assembler you never have to hand-decode a nibble again.
 */

#include "brad_as.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *progname = "bradasm";

static void usage(FILE *f)
{
    fprintf(f,
        "usage: %s [options] <source.s>\n"
        "\n"
        "  -o FILE     write the binary image here (default: a.bin)\n"
        "  -V FILE     write a Verilog boot-ROM include here instead\n"
        "  -m FILE     write one '%%08X' hex word per line (what testbenches\n"
        "              $readmemh / textio-load from the assembler's output)\n"
        "  -e ADDR     override the entry point\n"
        "  -l          print a listing: address, encoded word, source\n"
        "  -s          print the symbol table\n"
        "  -S          print symbols and exit without writing an image\n"
        "  -q          quiet: no output on success\n"
        "  -h          this help\n"
        "\n"
        "bradasm assembles BradISA V1. It emits 32-bit instructions only:\n"
        "the shipped core has no compressed decode path, so C.* forms are\n"
        "rejected rather than silently mistranslated.\n",
        progname);
}

/* Read a whole file into memory.  Caller frees. */
static char *read_file(const char *path)
{
    FILE *f = fopen(path, "rb");
    long n;
    char *buf;

    if (f == NULL) {
        fprintf(stderr, "%s: cannot open %s\n", progname, path);
        return NULL;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        fprintf(stderr, "%s: %s is not seekable\n", progname, path);
        return NULL;
    }
    n = ftell(f);
    if (n < 0) {
        fclose(f);
        fprintf(stderr, "%s: cannot size %s\n", progname, path);
        return NULL;
    }
    rewind(f);

    buf = (char *)malloc((size_t)n + 1u);
    if (buf == NULL) {
        fclose(f);
        fprintf(stderr, "%s: out of memory\n", progname);
        return NULL;
    }
    if (n > 0 && fread(buf, 1, (size_t)n, f) != (size_t)n) {
        fprintf(stderr, "%s: short read on %s\n", progname, path);
        free(buf);
        fclose(f);
        return NULL;
    }
    buf[n] = '\0';
    fclose(f);
    return buf;
}

/* Emit the image as a Verilog include for an RTL file that owns an
 * instruction memory called `imem`.  This is how the Tang Nano 9K boot ROM
 * reaches the board top without anyone hand-writing a hex literal again.
 *
 * It is emitted as an `initial begin` assignment block, not a packed localparam
 * array: every simulator and synthesizer this tree uses (iverilog, yosys,
 * verilator) accepts initial-block ROM fills, while unpacked-array assignment
 * patterns are a SystemVerilog feature that iverilog still declines. */
static int write_verilog(const char *path, const char *stem,
                         const struct brad_as_output *out, int quiet)
{
    FILE *f = fopen(path, "w");
    size_t i;
    size_t words = out->code_words;

    if (f == NULL) {
        fprintf(stderr, "%s: cannot write %s\n", progname, path);
        return 1;
    }
    fprintf(f, "// Generated by bradasm from %s -- do not edit.\n", stem);
    fprintf(f, "// %zu word%s at 0x%08x.\n", words, words == 1 ? "" : "s",
            out->base_addr);
    fprintf(f, "initial begin\n");
    for (i = 0; i < words; i++)
        fprintf(f, "    imem[%u] = 32'h%08X;\n",
                (unsigned)(out->base_addr / 4u + i), out->code[i]);
    fprintf(f, "end\n");
    if (fclose(f) != 0) {
        fprintf(stderr, "%s: short write on %s\n", progname, path);
        return 1;
    }
    if (!quiet)
        printf("%s: %zu word%s -> %s\n", progname, words, words == 1 ? "" : "s",
               path);
    return 0;
}

static void print_symbols(const struct brad_as_output *out)
{
    size_t i;

    printf("; %zu symbol%s\n", out->symbol_count,
           out->symbol_count == 1 ? "" : "s");
    for (i = 0; i < out->symbol_count; i++)
        printf("%-24s 0x%08x\n", out->symbols[i].name, out->symbols[i].addr);
    printf("entry 0x%08x\n", out->entry_point);
}

/* One uppercase-hex word per line, in address order: the memory-image format
 * iverilog's $readmemh and GHDL's textio/read both speak natively.  The
 * whole point is that a testbench which loads this file executes precisely
 * the words bradasm produced, no hand-encoded literals anywhere. */
static int write_mem(const char *path, const struct brad_as_output *out,
                     int quiet)
{
    FILE *f = fopen(path, "w");
    size_t i;

    if (f == NULL) {
        fprintf(stderr, "%s: cannot write %s\n", progname, path);
        return 1;
    }
    for (i = 0; i < out->code_words; i++)
        fprintf(f, "%08X\n", out->code[i]);
    if (fclose(f) != 0) {
        fprintf(stderr, "%s: short write on %s\n", progname, path);
        return 1;
    }
    if (!quiet)
        printf("%s: %zu word%s -> %s\n", progname, out->code_words,
               out->code_words == 1 ? "" : "s", path);
    return 0;
}

/* Split the source into a line-indexed array of pointers, so a listing row
 * (which knows its own line number) can be paired with the text it came
 * from.  The text is copied so trailing whitespace can be trimmed in place. */
static char **split_lines(const char *src, size_t *count)
{
    size_t n = 1, i;
    char **out;
    const char *p;

    for (p = src; *p; p++)
        if (*p == '\n')
            n++;

    out = (char **)calloc(n, sizeof *out);
    if (out == NULL)
        return NULL;

    p = src;
    for (i = 0; i < n; i++) {
        const char *eol = strchr(p, '\n');
        size_t len = eol ? (size_t)(eol - p) : strlen(p);
        char *copy = (char *)malloc(len + 1);
        if (copy == NULL) {
            size_t k;
            for (k = 0; k < i; k++)
                free(out[k]);
            free(out);
            return NULL;
        }
        memcpy(copy, p, len);
        copy[len] = '\0';
        out[i] = copy;
        if (eol == NULL) {
            i++;
            break;
        }
        p = eol + 1;
    }
    *count = i;
    return out;
}

/* The listing comes from the assembler's own records, not from a second
 * parse of the source.  The first version of this function re-read the text
 * looking for things that were not comments, which listed every prose line
 * in a well-commented file as an instruction.  An assembler that invents an
 * instruction for every sentence is not a tool anybody wants. */
static void print_listing(const char *src, const struct brad_as_listing *rows,
                          size_t nrows)
{
    size_t nlines = 0, i;
    char **lines = split_lines(src, &nlines);

    if (lines == NULL) {
        fprintf(stderr, "%s: out of memory building the listing\n", progname);
        return;
    }

    for (i = 0; i < nrows; i++) {
        char *text = (rows[i].line >= 1 && rows[i].line <= nlines)
                         ? lines[rows[i].line - 1] : (char *)"";
        size_t len = strlen(text);

        /* "loop: ADDI r1, r1, 1" produces both a label row and an instruction
         * row on the same line.  Print the line once. */
        if (!rows[i].has_word && i + 1 < nrows &&
            rows[i + 1].line == rows[i].line)
            continue;

        while (len > 0 && (text[len - 1] == ' ' || text[len - 1] == '\t' ||
                           text[len - 1] == '\r'))
            text[--len] = '\0';
        while (*text == ' ' || *text == '\t')
            text++;

        if (rows[i].has_word)
            printf("%4u  0x%08x  %08x  %s\n", rows[i].line, rows[i].addr,
                   rows[i].word, text);
        else
            printf("%4u  0x%08x  --------  %s\n", rows[i].line, rows[i].addr,
                   text);
    }

    for (i = 0; i < nlines; i++)
        free(lines[i]);
    free(lines);
}

int main(int argc, char **argv)
{
    const char *inpath = NULL;
    const char *outpath = "a.bin";
    const char *vlogpath = NULL;
    const char *mempath = NULL;
    char *src;
    struct brad_as_output *out;
    int do_listing = 0, do_syms = 0, quiet = 0, syms_only = 0;
    long entry_override = -1;
    int i, rc = 0;
    FILE *f;

    if (argc > 0 && argv[0] && *argv[0])
        progname = argv[0];

    for (i = 1; i < argc; i++) {
        const char *a = argv[i];
        if (a[0] == '-' && a[1] != '\0') {
            if (strcmp(a, "-o") == 0 && i + 1 < argc) {
                outpath = argv[++i];
            } else if (strcmp(a, "-V") == 0 && i + 1 < argc) {
                vlogpath = argv[++i];
            } else if (strcmp(a, "-m") == 0 && i + 1 < argc) {
                mempath = argv[++i];
            } else if (strcmp(a, "-e") == 0 && i + 1 < argc) {
                entry_override = strtol(argv[++i], NULL, 0);
            } else if (strcmp(a, "-l") == 0) {
                do_listing = 1;
            } else if (strcmp(a, "-s") == 0) {
                do_syms = 1;
            } else if (strcmp(a, "-S") == 0) {
                do_syms = syms_only = 1;
            } else if (strcmp(a, "-q") == 0) {
                quiet = 1;
            } else if (strcmp(a, "-h") == 0 || strcmp(a, "--help") == 0) {
                usage(stdout);
                return 0;
            } else {
                fprintf(stderr, "%s: unknown option %s\n", progname, a);
                usage(stderr);
                return 2;
            }
        } else {
            if (inpath) {
                fprintf(stderr, "%s: one source file at a time\n", progname);
                return 2;
            }
            inpath = a;
        }
    }

    if (inpath == NULL) {
        usage(stderr);
        return 2;
    }

    src = read_file(inpath);
    if (src == NULL)
        return 1;

    out = (struct brad_as_output *)malloc(sizeof *out);
    if (out == NULL) {
        fprintf(stderr, "%s: out of memory\n", progname);
        free(src);
        return 1;
    }

    if (do_listing) {
        /* Two passes: count the rows, then ask for them.  Cheaper than
         * guessing a capacity and truncating a listing with no warning. */
        size_t nrows = brad_as_assemble_listing(src, out, NULL, 0);
        struct brad_as_listing *rows;

        if (!out->err.ok) {
            fprintf(stderr, "%s: %s:%u: %s\n", progname, inpath,
                    out->err.line, out->err.error);
            free(out);
            free(src);
            return 1;
        }
        rows = (struct brad_as_listing *)malloc(nrows * sizeof *rows + 1);
        if (rows == NULL) {
            fprintf(stderr, "%s: out of memory\n", progname);
            free(out);
            free(src);
            return 1;
        }
        (void)brad_as_assemble_listing(src, out, rows, nrows);
        print_listing(src, rows, nrows);
        free(rows);
    } else if (brad_as_assemble(src, out) != 0) {
        fprintf(stderr, "%s: %s:%u: %s\n", progname, inpath,
                out->err.line, out->err.error);
        free(out);
        free(src);
        return 1;
    }

    if (entry_override >= 0) {
        out->entry_point = (uint32_t)entry_override;
        out->have_entry = 1;
    }

    if (do_syms)
        print_symbols(out);

    if (vlogpath != NULL) {
        rc |= write_verilog(vlogpath, inpath, out, quiet);
    }
    if (mempath != NULL) {
        rc |= write_mem(mempath, out, quiet);
    }

    if (!syms_only && vlogpath == NULL && mempath == NULL) {
        f = fopen(outpath, "wb");
        if (f == NULL) {
            fprintf(stderr, "%s: cannot write %s\n", progname, outpath);
            rc = 1;
        } else {
            /* Flat image, little-endian, covering the emitted span. */
            size_t nbytes = (size_t)(out->limit_addr - out->base_addr);
            uint8_t *bytes = (uint8_t *)malloc(nbytes ? nbytes : 1u);
            uint32_t a;
            size_t k = 0;

            if (bytes == NULL) {
                fprintf(stderr, "%s: out of memory\n", progname);
                rc = 1;
            } else {
                for (a = out->base_addr; a < out->limit_addr; a++) {
                    if (!brad_as_byte(out, a, &bytes[k]))
                        bytes[k] = 0;
                    k++;
                }
                if (fwrite(bytes, 1, k, f) != k) {
                    fprintf(stderr, "%s: short write on %s\n", progname,
                            outpath);
                    rc = 1;
                }
                free(bytes);
            }
            fclose(f);
        }
    }

    if (!quiet && !do_listing && !do_syms && vlogpath == NULL &&
        mempath == NULL) {
        printf("%s: %zu word%s, entry 0x%08x -> %s\n", progname,
               out->code_words, out->code_words == 1 ? "" : "s",
               out->entry_point, outpath);
    }

    free(out);
    free(src);
    return rc;
}
